### ISSUE TITLE
Panic running v12

### ISSUE THREAD

**Issue by Xymist** [XAMPPRocky/tokei#567]
After updating to the latest version and running (for curiosity) against the largest repo I have access to, I immediately get the following panic:

```
thread '<unnamed>' panicked at 'index 1 out of range for slice of length 0', src/libcore/slice/mod.rs:2725:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2725
  14: <[u8] as tokei::utils::ext::SliceExt>::trim_first_and_last_line_of_whitespace
  15: tokei::language::syntax::SyntaxCounter::perform_multi_line_analysis
  16: tokei::language::language_type::LanguageType::parse_lines
  17: std::panicking::try::do_call
  18: rayon_core::join::join
  19: tokei::language::language_type::LanguageType::parse
  20: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume
  21: <rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with
  22: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  23: std::panicking::try::do_call
  24: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  25: rayon_core::registry::WorkerThread::wait_until_cold
  26: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: “env RUST_BACKTRACE=1 tokei” terminated by signal SIGABRT (Abort)
```

The repo in question is a large but fairly standard Rails project. Unfortunately it's also closed source, but if there's any way I can assist with finding a cause do let me know.

**Comment by nil4** [comment]
Same here; running [tokei-x86_64-pc-windows-msvc.exe](https://github.com/XAMPPRocky/tokei/releases/download/v12.0.0/tokei-x86_64-pc-windows-msvc.exe) v12.0.0 on Windows results in: `thread '<unnamed>' panicked at 'index 1 out of range for slice of length 0', src\utils\ext.rs:51:10`

The backtrace with `RUST_BACKTRACE=full` is a lot less useful, unfortunately:
<details>
<pre><code>
thread '&lt;unnamed>' panicked at 'index 1 out of range for slice of length 0', src\utils\ext.rs:51:10
stack backtrace:
   0:     0x7ff70c9607a6 - <unknown>
   1:     0x7ff70c868eeb - <unknown>
   2:     0x7ff70c95d069 - <unknown>
   3:     0x7ff70c962fb2 - <unknown>
   4:     0x7ff70c96371b - <unknown>
   5:     0x7ff70c9630ba - <unknown>
   6:     0x7ff70c867510 - <unknown>
   7:     0x7ff70c86a8e7 - <unknown>
   8:     0x7ff70c9a4899 - <unknown>
   9:     0x7ff70c9a0b55 - <unknown>
  10:     0x7ff70c99a39c - <unknown>
  11:     0x7ff70c992328 - <unknown>
  12:     0x7ff70c96bc48 - <unknown>
  13:     0x7ff70ca0afb4 - <unknown>
  14:     0x7ff70ca44f5c - <unknown>
  15:     0x7ff70ca4dcd1 - <unknown>
  16:     0x7ff70ca13f2a - <unknown>
  17:     0x7ff70c8bc885 - <unknown>
  18:     0x7ff70c8bbb04 - <unknown>
  19:     0x7ff70c8bfb13 - <unknown>
  20:     0x7ff70c8bd4fd - <unknown>
  21:     0x7ff70c9662ae - <unknown>
  22:     0x7ffbf1066fd4 - BaseThreadInitThunk
  23:     0x7ffbf1bfcec1 - RtlUserThreadStart
thread '&lt;unnamed>' panicked at 'index 1 out of range for slice of length 0', src\utils\ext.rs:51:10
stack backtrace:
   0:     0x7ff70c9607a6 - <unknown>
   1:     0x7ff70c868eeb - <unknown>
   thread '&lt;unnamed>' panicked at 'index 1 out of range for slice of length 0', src\utils\ext.rs:51:10
2:     0x7ff70c95d069 - <unknown>
   3:     0x7ff70c962fb2 - <unknown>
   4:     0x7ff70c96371b - <unknown>
   5:     0x7ff70c9630ba - <unknown>
   6:     0x7ff70c867510 - <unknown>
   7:     0x7ff70c86a8e7 - <unknown>
   8:     0x7ff70c9a4899 - <unknown>
   9:     0x7ff70c9a0b55 - <unknown>
  10:     0x7ff70c99a39c - <unknown>
  11:     0x7ff70c992328 - <unknown>
  12:     0x7ff70c96bc48 - <unknown>
  13:     0x7ff70ca0afb4 - <unknown>
  14:     0x7ff70ca44f5c - <unknown>
  15:     0x7ff70ca4dcd1 - <unknown>
  16:     0x7ff70ca13f2a - <unknown>
  17:     0x7ff70c8bc885 - <unknown>
  18:     0x7ff70c8bbb04 - <unknown>
  19:     0x7ff70c8bfb13 - <unknown>
  20:     0x7ff70c8bd4fd - <unknown>
  21:     0x7ff70c9662ae - <unknown>
  22:     0x7ffbf1066fd4 - BaseThreadInitThunk
  23:     0x7ffbf1bfcec1 - RtlUserThreadStart
stack backtrace:
   0:     0x7ff70c9607a6 - <unknown>
   1:     0x7ff70c868eeb - <unknown>
   2:     0x7ff70c95d069 - <unknown>
   3:     0x7ff70c962fb2 - <unknown>
   4:     0x7ff70c96371b - <unknown>
   5:     0x7ff70c9630ba - <unknown>
   6:     0x7ff70c867510 - <unknown>
   7:     0x7ff70c86a8e7 - <unknown>
   8:     0x7ff70c9a4899 - <unknown>
   9:     0x7ff70c9a0b55 - <unknown>
  10:     0x7ff70c99a39c - <unknown>
  11:     0x7ff70c992328 - <unknown>
  12:     0x7ff70c96bc48 - <unknown>
  13:     0x7ff70ca0afb4 - <unknown>
  14:     0x7ff70ca44f5c - <unknown>
  15:     0x7ff70ca4dcd1 - <unknown>
  16:     0x7ff70ca13f2a - <unknown>
  17:     0x7ff70c8bc885 - <unknown>
  18:     0x7ff70c8bbb04 - <unknown>
  19:     0x7ff70c8bfb13 - <unknown>
  20:     0x7ff70c8bd4fd - <unknown>
  21:     0x7ff70c9662ae - <unknown>
  22:     0x7ffbf1066fd4 - BaseThreadInitThunk
  23:     0x7ffbf1bfcec1 - RtlUserThreadStart
</code></pre>
</details>

**Comment by baslas** [comment]
I have the same issue with 12.0.1 on Windows 10 and CentOS 7. It works well with 11.2.1. By the way it is my first time using Tokei, the speed is impressive!

<details>
<summary>Details:</summary>
<p>

```
thread '<unnamed>' panicked at 'index 2 out of range for slice of length 1', src/utils/ext.rs:55:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2751
  14: <[u8] as tokei::utils::ext::SliceExt>::trim_first_and_last_line_of_whitespace
  15: tokei::language::syntax::SyntaxCounter::perform_multi_line_analysis
  16: tokei::language::language_type::LanguageType::parse_lines
  17: rayon_core::registry::in_worker
  18: tokei::language::language_type::LanguageType::parse
  19: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume
  20: <rayon::iter::filter_map::FilterMapFolder<C,P> as rayon::iter::plumbing::Folder<T>>::consume
  21: <rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with
  22: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  23: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  24: rayon_core::registry::WorkerThread::wait_until_cold
  25: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

</p>
</details>

**Comment by XAMPPRocky** [comment]
@baslas I've just published 12.0.2 which should contain a fix for you.

**Comment by baslas** [comment]
12.0.3 did the trick, thanks!
